### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by SurelySomeday** [wgzeyu/12864playbadapple#2]
我下载了字模，让esp8266通过wifi直接访问txt文件获取数据，每一个txt文件内容是1408字节，但我看的你写的代码每次读取704字节，我试过每次读取704和1408都无法正常显示，请问一下这是什么原因。(我对单片机这一块不太熟悉)

**Comment by WGzeyu** [comment]
字模是txt格式，通过16进制来保存内容，每两个字符为一个字节，1408÷2=704

**Comment by WGzeyu** [comment]
突然又翻到了这个issue，补充一下，我提供的字模是通过16进制文本来存储的，每一个字节被转换成了两个字母，你不能直接读文本把字母发过去，需要先还原格式。
